import axios from "axios";

export const api = axios.create({
  baseURL: "https://localhost:7297",
});

api.defaults.headers.common["Authorization"] =
  "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6ImYzZjk5ODY2LWY3NDMtNDk0Yi04ZGVhLWJkMTRjMmE5YjBlNiIsIkxvZ2luIjoiYWxlIiwiQWN0aXZlIjoiYWxlIiwiRXhwaXJhdGlvbkRhdGUiOiIxMi8wNS8yMDIyIDAwOjAwOjAwIiwibmJmIjoxNjUyMjM4NDk5LCJleHAiOjE2NTIzMjQ0MDAsImlhdCI6MTY1MjIzODQ5OSwiaXNzIjoic2VsZiIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyOTc7aHR0cDovL2xvY2FsaG9zdDo1Mjk3In0.fRCSj33AIUaV8LaYMkeihC_Ary-fAFhNp5lKnWs-l7s";
